name: Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install Electron build tools
        run: npm i -g @electron/build-tools
        
      - name: Config
        run: e init release -i release -r ./build --fork leo-hydraulic/electron
        
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          repository: leo-hydraulic/electron
          path: ./build/src/electron
          ref: v23.0.0-hydraulic
          
      - name: Sync
        run: e sync
       
      - name: Build
        run: e build

      - name: List results
        run: ls ./build/src/out
