name: Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Test
        run: echo testing
